// Icon builder token groups for the Icon documentation (maintain alongside ulx icon.less @ulx-builder usage).

export default {
  'normal size': [
    's11',
    's12',
    's13',
    's14',
    's16',
    's18',
    's20',
    's22',
    's24',
    's26',
    's28',
    's30',
    's32'
  ],
  colors: [
    'primary',
    'success',
    'warning',
    'danger',
    'info',
    'muted',
    'inverted'
  ],
  'shaped icons size': [
    'xs',
    'sm',
    'md',
    'lg',
    'xl',
    'xl2',
    'xl3',
    'xl4',
    'xl5',
    'xl6',
    'xl7'
  ],
  layers: [
    'primary-layer1',
    'primary-layer',
    'primary-layer2',
    'success-layer',
    'success-layer2',
    'success-layer3',
    'warning-layer',
    'warning-layer2',
    'warning-layer3',
    'danger-layer',
    'danger-layer2',
    'danger-layer3',
    'info-layer',
    'info-layer2',
    'info-layer3',
    'blue-layer1',
    'blue-layer2',
    'blue-layer3',
    'purple-layer',
    'purple-layer2',
    'purple-layer3',
    'purple-layer4',
    'gold-layer',
    'gold-layer2',
    'gold-layer3',
    'black-layer',
    'black-layer2',
    'black-layer3',
    'black-layer4',
    'magenta-layer2',
    'brown-layer2',
    'teal-layer3'
  ],
  spin: ['spin-anim']
};
