/**
 * Demo-owned ULX message resource.
 * This keeps the demo runnable without Eventz.
 */
const ulxEnUsMessages = {
  'label.add': 'Add',
  'label.anonymous': 'Anonymous',
  'label.ascending': 'Ascending',
  'label.back': 'Back',
  'label.cancel': 'Cancel',
  'label.close': 'Close',
  'label.confirm': 'Confirm',
  'label.descending': 'Descending',
  'label.hide.password': 'Hide Password',
  'label.image': 'Image',
  'label.loading': 'Loading',
  'label.next': 'Next',
  'label.notifications': 'Notifications',
  'label.off': 'Off',
  'label.on': 'On',
  'label.previous': 'Prev',
  'label.rating': 'Rating',
  'label.remove': 'Remove',
  'label.restore': 'Restore',
  'label.save': 'Save',
  'label.search': 'Search',
  'label.select.all': 'Select All',
  'label.show.password': 'Show Password',
  'lbl.records.per.page': 'Records per Page',
  'lbl.a11y.empty.state.content': 'Empty state content',
  'lbl.add.filter.rule': 'Add rule',
  'lbl.apply.filter': 'Apply Filter',
  'lbl.clear': 'Clear',
  'lbl.clear.filters': 'Clear filters',
  'lbl.clear.selection': 'Clear selection',
  'lbl.close.notification': 'Close notification',
  'lbl.columns': 'Columns',
  'lbl.datepicker.clear': 'Clear date',
  'lbl.datepicker.placeholder': 'Select date',
  'lbl.datepicker.toggle': 'Open calendar',
  'lbl.daterangepicker.placeholder': 'Select date range',
  'lbl.delete.filter': 'Delete filter',
  'lbl.editor.letter.spacing': 'Letter spacing',
  'lbl.editor.line.height': 'Line height',
  'lbl.editor.placeholder': 'Type here...',
  'lbl.editor.toolbar.blockquote': 'Blockquote',
  'lbl.editor.toolbar.bold': 'Bold',
  'lbl.editor.toolbar.clean': 'Clear formatting',
  'lbl.editor.toolbar.code.block': 'Code block',
  'lbl.editor.toolbar.hr': 'Horizontal rule',
  'lbl.editor.toolbar.image': 'Insert image',
  'lbl.editor.toolbar.indent.decrease': 'Decrease indent',
  'lbl.editor.toolbar.indent.increase': 'Increase indent',
  'lbl.editor.toolbar.italic': 'Italic',
  'lbl.editor.toolbar.link': 'Insert link',
  'lbl.editor.toolbar.list.bullet': 'Bulleted list',
  'lbl.editor.toolbar.list.ordered': 'Numbered list',
  'lbl.editor.toolbar.picker.align': 'Alignment',
  'lbl.editor.toolbar.picker.background': 'Background color',
  'lbl.editor.toolbar.picker.color': 'Text color',
  'lbl.editor.toolbar.picker.font': 'Font',
  'lbl.editor.toolbar.picker.font.family': 'Font family',
  'lbl.editor.toolbar.picker.header': 'Heading',
  'lbl.editor.toolbar.picker.letter.spacing': 'Letter spacing',
  'lbl.editor.toolbar.picker.line.height': 'Line height',
  'lbl.editor.toolbar.picker.size': 'Font size',
  'lbl.editor.toolbar.picker.text.transform': 'Text transform',
  'lbl.editor.toolbar.region': 'Editor toolbar',
  'lbl.editor.toolbar.strike': 'Strikethrough',
  'lbl.editor.toolbar.subscript': 'Subscript',
  'lbl.editor.toolbar.superscript': 'Superscript',
  'lbl.editor.toolbar.underline': 'Underline',
  'lbl.editor.toolbar.zia': 'Improve writing',
  'lbl.enter.value': 'Enter a value',
  'lbl.filter': 'Filter',
  'lbl.filter.and': 'AND',
  'lbl.filter.contains': 'Contains',
  'lbl.filter.ends.with': 'Ends with',
  'lbl.filter.equals': 'Equals',
  'lbl.filter.in': 'In',
  'lbl.filter.not.contains': 'Not contains',
  'lbl.filter.not.equals': 'Not equals',
  'lbl.filter.not.in': 'Not in',
  'lbl.filter.or': 'OR',
  'lbl.filter.starts.with': 'Starts with',
  'lbl.manage.columns': 'Manage Columns',
  'lbl.maximize': 'Maximize',
  'lbl.more.options': 'More options',
  'lbl.paginator.choose': 'Choose',
  'lbl.password.medium': 'Medium',
  'lbl.password.prompt': 'Please enter a password',
  'lbl.password.strong': 'Strong',
  'lbl.password.weak': 'Weak',
  'lbl.progress.decrease': 'Decrease value',
  'lbl.progress.increase': 'Increase value',
  'lbl.rating.cancel': 'Reset rating',
  'lbl.reset.to.default': 'Reset to Default',
  'lbl.search': 'Search',
  'lbl.select': 'Select',
  'lbl.slider': 'Slider',
  'lbl.slider.handleEnd': 'End',
  'lbl.slider.handleStart': 'Start',
  'lbl.sort': 'Sort',
  'lbl.sorter': 'Sorter',
  'lbl.view.less': 'View less',
  'lbl.view.more': 'View more',
  'label.no.results.found': 'No results found.',
  'lbl.timepicker.placeholder': 'Select time',
  'lbl.timepicker.format12': '12-hour',
  'lbl.timepicker.format24': '24-hour',
  'lbl.timepicker.toggle': 'Open time picker',
  'msg.empty.state.subtitle': 'Try adjusting your filters or search.',
  'msg.empty.state.title': 'No results',
  'msg.image.load.failed': 'Failed to load',
  'msg.more.members': '{count} more members',
  'msg.multiselect.empty': 'No options',
  'msg.multiselect.filter.placeholder': 'Search',
  'msg.multiselect.items.selected': '{count} items selected',
  'msg.multiselect.placeholder': 'Select items',
  'msg.table.column.moved': 'Moved column {header} to position {position}.',
  'msg.table.enter.filter.value': 'Enter filter value',
  'msg.table.global.filter.placeholder': 'Search...',
  'msg.table.no.records': 'No records found.',
  'msg.table.select.values': 'Select values',
  'lbl.a11y.dataview.region': 'Data view',
  'lbl.a11y.datepicker.nextMonth': 'Go to next month',
  'lbl.a11y.datepicker.previousMonth': 'Go to previous month',
  'lbl.a11y.dropdown.open': 'Open options',
  'lbl.a11y.field.moreInformation': 'More information',
  'lbl.a11y.chipInput.addChip': 'Add chip',
  'lbl.a11y.chipInput.remove': 'Remove {chip}',
  'lbl.a11y.paginator.firstPage': 'First page',
  'lbl.a11y.paginator.lastPage': 'Last page',
  'lbl.a11y.paginator.navigation': 'Pagination navigation',
  'lbl.a11y.paginator.nextPage': 'Next page',
  'lbl.a11y.paginator.pageLabel': 'Page {page}',
  'lbl.a11y.paginator.prevPage': 'Previous page',
  'lbl.a11y.paginator.rowsPerPage': 'Rows per page',
  'lbl.a11y.table.cancel.editing': 'Cancel editing',
  'lbl.a11y.table.collapse.row': 'Collapse row',
  'lbl.a11y.table.column.filter': 'Column filter',
  'lbl.a11y.table.drag.reorder': 'Drag to reorder',
  'lbl.a11y.table.edit.row': 'Edit row',
  'lbl.a11y.table.expand.row': 'Expand row',
  'lbl.a11y.table.filter.column': 'Filter column {header}',
  'lbl.a11y.table.filter.match.mode': 'Filter match mode',
  'lbl.a11y.table.filter.operator': 'Filter operator',
  'lbl.a11y.table.filter.value': 'Filter value',
  'lbl.a11y.table.filter.values': 'Filter values',
  'lbl.a11y.table.global.filter': 'Search table',
  'lbl.a11y.table.loading': 'Loading data',
  'lbl.a11y.table.move.column.down': 'Move column {header} down',
  'lbl.a11y.table.move.column.up': 'Move column {header} up',
  'lbl.a11y.table.remove.filter.rule': 'Remove filter rule',
  'lbl.a11y.table.save.row': 'Save row',
  'lbl.a11y.table.select.all': 'Select all rows',
  'lbl.a11y.table.select.row': 'Select row {index}',
  'lbl.a11y.table.show.filter.menu': 'Show filter menu',
  'lbl.a11y.table.toggle.column': 'Toggle column {header}',
  'lbl.a11y.table.toolbar.filter.active': 'Filter, {count} active',
  'lbl.a11y.table.vertical.corner': 'Property',
  'lbl.a11y.table.view.card': 'Card view',
  'lbl.a11y.table.view.detailed': 'Detailed view',
  'lbl.a11y.table.view.table': 'Table view',
  'lbl.a11y.table.view.toggle': 'View layout'
};

export default ulxEnUsMessages;
